#include "polynomial.h"
#include "de_casteljau.h"

/**
 * @file polynomial.cpp
 * @brief Implementation of the Polynomial class
 */

#include <algorithm>

namespace {

// Compute strides for a tensor-product layout where the last dimension
// varies fastest.
void compute_strides(const std::vector<unsigned int>& degrees,
                     std::vector<std::size_t>& strides)
{
    const std::size_t dim = degrees.size();
    strides.assign(dim, 0u);

    std::size_t s = 1u;
    for (std::size_t k = dim; k-- > 0;) {
        strides[k] = s;
        s *= static_cast<std::size_t>(degrees[k] + 1u);
    }
}

// Flatten a multi-index using precomputed strides.
std::size_t flatten_index(const std::vector<unsigned int>& multi_index,
                          const std::vector<std::size_t>& strides)
{
    std::size_t idx = 0u;
    const std::size_t dim = multi_index.size();
    for (std::size_t k = 0; k < dim; ++k) {
        idx += static_cast<std::size_t>(multi_index[k]) * strides[k];
    }
    return idx;
}

// Increment a multi-index over all dimensions except the given axis.
// Returns false when all combinations have been exhausted.
bool increment_multi_except_axis(std::vector<unsigned int>& index,
                                 const std::vector<unsigned int>& degrees,
                                 std::size_t axis)
{
    const std::size_t dim = degrees.size();

    for (std::size_t d = dim; d-- > 0;) {
        if (d == axis) {
            continue;
        }
        if (index[d] < degrees[d]) {
            ++index[d];
            // Reset all dimensions greater than d (except axis) to zero.
            for (std::size_t e = d + 1; e < dim; ++e) {
                if (e == axis) {
                    continue;
                }
                index[e] = 0u;
            }
            return true;
        }
    }

    return false;
}

// Convert 1D power-basis coefficients to Bernstein coefficients using
// an iterative scheme that avoids explicit binomial coefficients.
// Based on the identity
//   b_k = sum_{i=0}^k a_i * C(k,i) / C(n,i),  0 <= k <= n,
// but the ratios C(k,i)/C(n,i) are generated by a stable downward
// recurrence in k for each fixed i.
void power_to_bernstein_1d(unsigned int degree,
                           const std::vector<double>& power_coeffs_1d,
                           std::vector<double>& bernstein_coeffs_1d)
{
    const std::size_t len = static_cast<std::size_t>(degree + 1u);
    bernstein_coeffs_1d.assign(len, 0.0);

    if (len == 0u) {
        return;
    }

    const int n = static_cast<int>(degree);

    // Accumulate contributions from each power-basis coefficient a_i.
    for (int i = 0; i <= n; ++i) {
        const double a_i = power_coeffs_1d[static_cast<std::size_t>(i)];

        // For fixed i, start from r_{n,i} = C(n,i)/C(n,i) = 1 and
        // move downward in k using
        //   r_{k,i} = r_{k+1,i} * (k + 1 - i) / (k + 1).
        double r = 1.0;

        // Contribution to k = n.
        bernstein_coeffs_1d[static_cast<std::size_t>(n)] += a_i * r;

        // Contributions to k = n-1, ..., i.
        for (int k = n - 1; k >= i; --k) {
            r *= static_cast<double>(k + 1 - i) / static_cast<double>(k + 1);
            bernstein_coeffs_1d[static_cast<std::size_t>(k)] += a_i * r;
        }
    }
}

} // anonymous namespace

namespace polynomial_solver {

Polynomial::Polynomial()
    : dimension_(0u)
{
}

Polynomial::Polynomial(const std::vector<unsigned int>& degrees,
                       const std::vector<double>& bernstein_coeffs)
    : dimension_(degrees.size()),
      degrees_(degrees),
      bernstein_coeffs_(bernstein_coeffs)
{
    // TODO: Optionally validate that bernstein_coeffs_.size()
    // matches coefficientCount().
}

Polynomial::~Polynomial() {
    // No special cleanup required.
}

Polynomial Polynomial::fromBernstein(const std::vector<unsigned int>& degrees,
                                     const std::vector<double>& bernstein_coeffs)
{
    // TODO: Add validation if needed.
    return Polynomial(degrees, bernstein_coeffs);
}

Polynomial Polynomial::fromPower(const std::vector<unsigned int>& degrees,
                                 const std::vector<double>& power_coeffs)
{
    // Compute expected number of coefficients.
    std::size_t count = 1u;
    for (std::size_t i = 0; i < degrees.size(); ++i) {
        count *= static_cast<std::size_t>(degrees[i] + 1u);
    }

    if (count == 0u) {
        return Polynomial(degrees, std::vector<double>());
    }

    // Copy and resize input coefficients as needed.
    std::vector<double> coeffs = power_coeffs;
    if (coeffs.size() < count) {
        coeffs.resize(count, 0.0);
    } else if (coeffs.size() > count) {
        coeffs.resize(count);
    }

    const std::size_t dim = degrees.size();
    if (dim == 0u) {
        return Polynomial(degrees, coeffs);
    }

    // Precompute strides for the tensor layout (last dimension fastest).
    std::vector<std::size_t> strides;
    compute_strides(degrees, strides);

    // Transform along each dimension separately from power basis to Bernstein.
    std::vector<unsigned int> multi_index(dim, 0u);

    for (std::size_t axis = 0; axis < dim; ++axis) {
        const unsigned int deg_axis = degrees[axis];
        const std::size_t len_axis = static_cast<std::size_t>(deg_axis + 1u);

        if (len_axis <= 1u) {
            continue; // nothing to do along this dimension
        }

        std::vector<double> line_in(len_axis);
        std::vector<double> line_out;

        std::fill(multi_index.begin(), multi_index.end(), 0u);
        bool first = true;

        while (first || increment_multi_except_axis(multi_index, degrees, axis)) {
            first = false;

            // Gather a 1D slice along the current axis.
            for (std::size_t k = 0; k < len_axis; ++k) {
                multi_index[axis] = static_cast<unsigned int>(k);
                const std::size_t idx = flatten_index(multi_index, strides);
                line_in[k] = coeffs[idx];
            }

            // Convert this slice from power basis to Bernstein basis.
            power_to_bernstein_1d(deg_axis, line_in, line_out);

            // Scatter converted coefficients back.
            for (std::size_t k = 0; k < len_axis; ++k) {
                multi_index[axis] = static_cast<unsigned int>(k);
                const std::size_t idx = flatten_index(multi_index, strides);
                coeffs[idx] = line_out[k];
            }
        }
    }

    return Polynomial(degrees, coeffs);
}

std::size_t Polynomial::dimension() const {
    return dimension_;
}

const std::vector<unsigned int>& Polynomial::degrees() const {
    return degrees_;
}

std::size_t Polynomial::coefficientCount() const {
    std::size_t count = 1u;
    for (std::size_t i = 0; i < degrees_.size(); ++i) {
        count *= static_cast<std::size_t>(degrees_[i] + 1u);
    }
    return count;
}

const std::vector<double>& Polynomial::bernsteinCoefficients() const {
    return bernstein_coeffs_;
}

double Polynomial::evaluate(const std::vector<double>& parameters) const {
    // TODO: Add input validation (parameters.size() == dimension_, etc.).
    return DeCasteljau::evaluateTensorProduct(degrees_, bernstein_coeffs_, parameters);
}

double Polynomial::evaluate(double t) const {
    // Convenience overload for the univariate case.
    std::vector<double> params(1u, t);
    return evaluate(params);
}

std::size_t Polynomial::flattenIndex(const std::vector<unsigned int>& multi_index) const {
    std::size_t idx = 0u;
    std::size_t stride = 1u;
    const std::size_t dim = degrees_.size();

    // Last dimension varies fastest.
    for (std::size_t d = dim; d-- > 0;) {
        idx += static_cast<std::size_t>(multi_index[d]) * stride;
        stride *= static_cast<std::size_t>(degrees_[d] + 1u);
    }

    return idx;
}

void Polynomial::graphControlPoints(std::vector<double>& control_points) const {
    const std::size_t dim = dimension_;
    const std::size_t coeff_count = coefficientCount();

    const std::size_t stride = dim + 1u;
    control_points.assign(coeff_count * stride, 0.0);

    if (coeff_count == 0u) {
        return;
    }

    std::vector<unsigned int> multi_index(dim, 0u);
    std::size_t idx = 0u;

    while (true) {
        const std::size_t base = idx * stride;

        // First dim coordinates: normalized parameter position.
        for (std::size_t j = 0; j < dim; ++j) {
            const unsigned int deg_j = degrees_[j];
            double coord = 0.0;
            if (deg_j > 0u) {
                coord = static_cast<double>(multi_index[j]) /
                        static_cast<double>(deg_j);
            }
            control_points[base + j] = coord;
        }

        // Last coordinate: function value (Bernstein coefficient).
        control_points[base + dim] = bernstein_coeffs_[idx];

        if (idx + 1u >= coeff_count) {
            break;
        }

        ++idx;

        // Increment multi-index with last dimension fastest.
        if (dim > 0u) {
            for (std::size_t d = dim; d-- > 0;) {
                if (multi_index[d] < degrees_[d]) {
                    ++multi_index[d];
                    for (std::size_t e = d + 1; e < dim; ++e) {
                        multi_index[e] = 0u;
                    }
                    break;
                }
            }
        }
    }
}


} // namespace polynomial_solver
